### ISSUE TITLE
Quite similar to another project?

### ISSUE THREAD

**Issue by JoshuaSenouf** [yoyo-sincerely/AwesomeRenderer#1]
Hey,

During my usual exploration of projects on GitHub, I came across this one. I first wondered why the README.md felt so familiar, until I went looking into the project itself, to realize most of the real-time rendering related code, whether it is C++ or GLSL,  was coming from my own project:

https://github.com/JoshuaSenouf/GLEngine

While I have no problems with people using and modifying my code to do whatever they want (I mean, it is freely available), I am having a bit of a problem with literal appropriation, without any credits or mention whatsoever of the original author in any file.

Thanks.

**Comment by yoyo-sincerely** [comment]
I will delete this project, I have to say that your project is awesome.
